name: 'cache node modules'
description: 'cache node modules'
runs:
  using: 'composite'
  steps:
    - uses: actions/cache@v3
      id: node_modules_cache_id
      env:
        cache-name: cache-node-modules
      with:
        path: '**/node_modules'
        key: ${{ runner.os }}-nodejs-${{ hashFiles('**/package-lock.json') }}
    - if: ${{ steps.node_modules_cache_id.outputs.cache-hit != 'true' }}
      name: install node_modules
      run: npm install
      shell: bash
