name: 'prepare for screenshots'
description: 'prepare for screenshots'
runs:
  using: 'composite'
  steps:
    - name: download chromium
      run: npm run download:chromium
      shell: bash

    - name: install native dependencies
      run: sudo apt-get install fonts-ipafont-gothic
      shell: bash
